DROP TABLE IF EXISTS MOVEMENT CASCADE;
DROP TABLE IF EXISTS ACCOUNT CASCADE;
DROP TABLE IF EXISTS BRANCH CASCADE;
DROP TABLE IF EXISTS BANK CASCADE;
DROP SEQUENCE IF EXISTS account_numSEQ;
DROP SEQUENCE IF EXISTS movement_numSEQ;
CREATE SEQUENCE account_numSEQ START 1;
CREATE SEQUENCE movement_numSEQ START 1;

CREATE TABLE BANK (
    BANK_ID INT PRIMARY KEY,
    BANK_NF VARCHAR(10),
    BANK_NAME VARCHAR(30),
    DOM_FISCAL VARCHAR(35),
    POBLATION VARCHAR(35)
);

CREATE TABLE BRANCH (
    BANK_ID INT,
    BRANCH_ID INT,
    BRANCH_NAME VARCHAR(35),
    BRANCH_LOC VARCHAR(35),
    SUC_PROV VARCHAR(35),
    PRIMARY KEY (BANK_ID, BRANCH_ID),
    FOREIGN KEY (BANK_ID) REFERENCES BANK(BANK_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE ACCOUNT (
    BANK_ID INT,
    BRANCH_ID INT,
    ACC_NUM VARCHAR(10),
    IBAN VARCHAR(34) UNIQUE,
    DNI VARCHAR(9),
    BALANCE NUMERIC(12,2),
    PRIMARY KEY (BANK_ID, BRANCH_ID, ACC_NUM),
    FOREIGN KEY (BANK_ID, BRANCH_ID) REFERENCES BRANCH(BANK_ID, BRANCH_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);


CREATE TABLE MOVEMENT (
    OP_ID INT PRIMARY KEY,
    BANK_ID INT,
    BRANCH_ID INT,
    ACC_NUM VARCHAR(10),
    DT DATE DEFAULT CURRENT_DATE,
    AMMOUNT NUMERIC(12,2),
    OP_TYPE VARCHAR(20),
    OBSERVATION VARCHAR(50),
    FOREIGN KEY (BANK_ID, BRANCH_ID, ACC_NUM) REFERENCES ACCOUNT(BANK_ID, BRANCH_ID, ACC_NUM)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

