DROP TABLE IF EXISTS MOVEMENT CASCADE;
DROP TABLE IF EXISTS ACCOUNT CASCADE;
DROP TABLE IF EXISTS BRANCH CASCADE;
DROP TABLE IF EXISTS BANK CASCADE;
DROP SEQUENCE IF EXISTS account_num_cta_seq;

CREATE SEQUENCE account_num_cta_seq START 1;

CREATE TABLE BANK (
    COD_BANCO INT PRIMARY KEY,
    NF_BANCO VARCHAR(10),
    NOMBRE_BANC VARCHAR(30),
    DOM_FISCAL VARCHAR(35),
    POBLACION VARCHAR(35)
);

CREATE TABLE BRANCH (
    COD_BANCO INT,
    COD_SUCUR INT,
    NOMBRE_SUC VARCHAR(35),
    LOC_SUC VARCHAR(35),
    PROV_SUC VARCHAR(35),
    PRIMARY KEY (COD_BANCO, COD_SUCUR),
    FOREIGN KEY (COD_BANCO) REFERENCES BANK(COD_BANCO) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE
);

CREATE TABLE ACCOUNT (
    COD_BANCO INT,
    COD_SUCUR INT,
    NUM_CTA BIGINT,
    IBAN VARCHAR(24) UNIQUE,
    DNI_DUENO VARCHAR(9),
    SALDO DOUBLE PRECISION,
    PRIMARY KEY (COD_BANCO, COD_SUCUR, NUM_CTA),
    FOREIGN KEY (COD_BANCO, COD_SUCUR) REFERENCES BRANCH(COD_BANCO, COD_SUCUR) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE
);


CREATE TABLE MOVEMENT (
    NUM_OPERAC INT PRIMARY KEY,
    COD_BANCO INT,
    COD_SUCUR INT,
    NUM_CTA BIGINT,
    FECHA DATE,
    CANTIDAD DOUBLE PRECISION,
    TIPO_OPERAC VARCHAR(20),
    OBSERVACION VARCHAR(50),
    FOREIGN KEY (COD_BANCO, COD_SUCUR, NUM_CTA) REFERENCES ACCOUNT(COD_BANCO, COD_SUCUR, NUM_CTA) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE
);
